use crate::block::types::block::Block;
use crate::utilities::crypto::Signature;

pub(crate) mod rocksdb;

pub(crate) trait EphemeraDatabase {
    /// Returns block by its id. Block ids are generated by Ephemera
    fn get_block_by_id(&self, block_id: String) -> anyhow::Result<Option<Block>>;
    /// Returns last committed/finalised block.
    fn get_last_block(&self) -> anyhow::Result<Option<Block>>;
    /// Returns block by its height
    fn get_block_by_height(&self, height: u64) -> anyhow::Result<Option<Block>>;
    fn get_block_signatures(&self, block_id: String) -> anyhow::Result<Option<Vec<Signature>>>;
    /// Stores block and its signatures
    fn store_block(&mut self, block: &Block, signatures: Vec<Signature>) -> anyhow::Result<()>;
}
