apiVersion: apps/v1
kind: Deployment
metadata:
  name: ephemera2-deployment
  labels:
    app: ephemera2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ephemera2
  template:
    metadata:
      labels:
        app: ephemera2
    spec:
      containers:
        - image: 526189391121.dkr.ecr.us-east-1.amazonaws.com/nym:ephemera
          imagePullPolicy: Always
          name: ephemera
          env:
            - name: EPHEMERA_CONFIG
              value: "/config/ephemera2.toml"
            - name: PEERS_CONFIG
              value: "/config/peers.toml"
            - name: RUST_LOG
              value: "ephemera=trace,info"
          volumeMounts:
            - mountPath: /config
              name: config
          ports:
            - containerPort: 3000
              name: protocol-port
            - containerPort: 7000
              name: http-port
      volumes:
        - name: config
          configMap:
            name: ephemera2
---
apiVersion: v1
kind: Service
metadata:
  name: ephemera2
spec:
  selector:
    app: ephemera2
  type: LoadBalancer
  ports:
    - name: protocol-port-svc
      protocol: TCP
      port: 3000
      targetPort: protocol-port
    - name: http-port-svc
      protocol: TCP
      port: 7000
      targetPort: http-port
