[build]
default-target = "x86_64-unknown-linux-gnu"
pre-build = [
    "apt-get update && apt-get --assume-yes install libssl-dev"
]

#wget http://nz2.archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl-dev_3.0.8-1ubuntu2_amd64.deb
#sudo ln -s /usr/lib/x86_64-linux-gnu/libssl.so /usr/lib/x86_64-linux-gnu/libssl.so.1.1
#sudo ln -s /usr/lib/x86_64-linux-gnu/libcrypto.so /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1
